### ISSUE TITLE
SMAPI Error

### ISSUE THREAD

**Issue by Ehan1213** [jamescodesthings/smapi-better-sprinklers#7] opened 2024-11-09 13:46 UTC
[Better Sprinklers Plus] This mod failed in the Display.RenderedWorld event. Technical details:
SContentLoadException: Better Sprinklers Plus failed loading content asset 'LooseSprites/buildingPlacementTiles' from the game content.
 ---> Microsoft.Xna.Framework.Content.ContentLoadException: The content file was not found.
 ---> FileNotFoundException: Could not find file 'C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Content\LooseSprites\buildingPlacementTiles.xnb'.
File name: 'C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Content\LooseSprites\buildingPlacementTiles.xnb'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Microsoft.Xna.Framework.TitleContainer.PlatformOpenStream(String safeName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Platform\TitleContainer.Desktop.cs:line 29
   at Microsoft.Xna.Framework.TitleContainer.OpenStream(String name) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\TitleContainer.cs:line 37
   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\MonoGame.Desktop\MonoGame.Framework\Content\ContentManager.cs:line 276
   --- End of inner exception stack trace ---

**Comment by rhettl** [comment] 2024-11-24 00:00
Bumping. Having the same issue. A user on Nexus mentioned grabbing the file from a older install and placing it in the right directory. I can't do this because I don't have an older install from which to grab the file.

**Comment by MDrift314** [comment] 2024-11-26 14:57
The issue is on line 19 of BetterSprinklersPlus/Framework/Helpers/GridHelper.cs
The mod references that is no longer included in the game, since nothing uses it. 

I've hosted the file here, if anyone finds this and needs it. 
https://www.mediafire.com/file/jlo8kbti0vnvxps/buildingPlacementTiles.xnb/file

**Comment by gingajamie** [comment] 2024-11-29 15:21
This should be fixed as of version 2.18.1.

**Closed as completed by gingajamie** 2024-11-29 15:21 UTC
